-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NotificationType" ADD VALUE 'INTERVIEW_REMINDER_24H';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVIEW_REMINDER_1H';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVIEW_RESCHEDULED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVIEW_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVIEW_FEEDBACK_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_REVIEWED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_STARTED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_STAGE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_OFFER_EXTENDED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_OFFER_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'HIRING_PROCESS_OFFER_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_STAGE_ADVANCED';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_STAGE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_ADDED_TO_PROCESS';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_REMOVED_FROM_PROCESS';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_NOTE_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'CANDIDATE_SCORE_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_INVITATION_SENT';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_INVITATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_INVITATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_INVITATION_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_MEMBER_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_MEMBER_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE 'TEAM_ROLE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPANY_CONNECTION_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPANY_CONNECTION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPANY_CONNECTION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPANY_SETTINGS_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_TRIAL_ENDING';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_TRIAL_ENDED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_PLAN_UPGRADED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_PLAN_DOWNGRADED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_PAYMENT_SUCCESS';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_RENEWED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_LIMIT_WARNING';
ALTER TYPE "NotificationType" ADD VALUE 'SUBSCRIPTION_LIMIT_REACHED';
ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_EMAIL_VERIFIED';
ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_PASSWORD_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_PROFILE_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_WELCOME';
ALTER TYPE "NotificationType" ADD VALUE 'JOB_POSITION_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'JOB_POSITION_PUBLISHED';
ALTER TYPE "NotificationType" ADD VALUE 'JOB_POSITION_CLOSED';
ALTER TYPE "NotificationType" ADD VALUE 'JOB_POSITION_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'SYSTEM_MAINTENANCE';
ALTER TYPE "NotificationType" ADD VALUE 'SYSTEM_ANNOUNCEMENT';
ALTER TYPE "NotificationType" ADD VALUE 'SYSTEM_FEATURE_UPDATE';
