services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: recruiting_tool_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build:
      context: ./recruiting-tool-backend
      dockerfile: Dockerfile
    ports:
      - '${API_PORT:-4000}:${API_PORT:-4000}'
    env_file:
      - ./recruiting-tool-backend/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/recruiting_tool_db
    volumes:
      - ./recruiting-tool-backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
