export enum NotificationType {
  // Interview notifications
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_BOOKED_BY_CANDIDATE = "INTERVIEW_BOOKED_BY_CANDIDATE",
  INTERVIEW_UPDATED = "INTERVIEW_UPDATED",
  INTERVIEW_CANCELLED = "INTERVIEW_CANCELLED",
  INTERVIEW_REMINDER_24H = "INTERVIEW_REMINDER_24H",
  INTERVIEW_REMINDER_1H = "INTERVIEW_REMINDER_1H",
  INTERVIEW_RESCHEDULED = "INTERVIEW_RESCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  INTERVIEW_FEEDBACK_SUBMITTED = "INTERVIEW_FEEDBACK_SUBMITTED",

  // Application notifications
  APPLICATION_RECEIVED = "APPLICATION_RECEIVED",
  APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED",
  APPLICATION_REVIEWED = "APPLICATION_REVIEWED",
  APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED",
  APPLICATION_REJECTED = "APPLICATION_REJECTED",
  APPLICATION_STATUS = "APPLICATION_STATUS",

  // Hiring process notifications
  HIRING_PROCESS_STARTED = "HIRING_PROCESS_STARTED",
  HIRING_PROCESS_STAGE_CHANGED = "HIRING_PROCESS_STAGE_CHANGED",
  HIRING_PROCESS_COMPLETED = "HIRING_PROCESS_COMPLETED",
  HIRING_PROCESS_OFFER_EXTENDED = "HIRING_PROCESS_OFFER_EXTENDED",
  HIRING_PROCESS_OFFER_ACCEPTED = "HIRING_PROCESS_OFFER_ACCEPTED",
  HIRING_PROCESS_OFFER_REJECTED = "HIRING_PROCESS_OFFER_REJECTED",

  // Candidate notifications
  CANDIDATE_STAGE_ADVANCED = "CANDIDATE_STAGE_ADVANCED",
  CANDIDATE_STAGE_REJECTED = "CANDIDATE_STAGE_REJECTED",
  CANDIDATE_ADDED_TO_PROCESS = "CANDIDATE_ADDED_TO_PROCESS",
  CANDIDATE_NOTE_ADDED = "CANDIDATE_NOTE_ADDED",
  CANDIDATE_SCORE_UPDATED = "CANDIDATE_SCORE_UPDATED",

  // Team management notifications
  TEAM_INVITATION_SENT = "TEAM_INVITATION_SENT",
  TEAM_INVITATION_ACCEPTED = "TEAM_INVITATION_ACCEPTED",
  TEAM_INVITATION_REJECTED = "TEAM_INVITATION_REJECTED",
  TEAM_INVITATION_EXPIRED = "TEAM_INVITATION_EXPIRED",
  TEAM_MEMBER_ADDED = "TEAM_MEMBER_ADDED",
  TEAM_MEMBER_REMOVED = "TEAM_MEMBER_REMOVED",

  // General system notifications
  SYSTEM = "SYSTEM",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
}

export interface Notification {
  uid: string;
  userUid: string;
  type: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  metadata?: Record<string, unknown> | null;
  createdAt: string;
  readAt?: string | null;
}

export interface CreateNotificationDto {
  userUid: string;
  type: NotificationType;
  title: string;
  message: string;
  metadata?: Record<string, unknown>;
}

export interface GetNotificationsQuery {
  isRead?: boolean;
  limit?: number;
  skip?: number;
}
